server {
    listen 80;

    root /usr/share/nginx/html;

    location /momo-store/ {
        try_files $uri $uri/ /momo-store/index.html;
    }
    
    # both frontend and backend containers should be run with the same --network
    location /api/ {
        proxy_pass http://backend:8081/;
    }

}