# version: "3.8" # the attribute `version` is obsolete

services:
  backend:
    container_name: backend
    build: ./backend/
    networks:
      - docker-network
    ports:
      - "8081:8081"
    cap_drop:
      - ALL
    read_only: true
    restart: on-failure

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      args:
        VUE_APP_API_URL: /api # can be something else, see nginx.conf with proxy_pass to backend
    networks:
      - docker-network
    ports:
      - "80:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro # instead of copying it in Dockerfile
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE # only because nginx uses a well-known port 80
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    restart: on-failure

networks:
  docker-network:
    driver: bridge
